[[application]]
name = "Trade Tariff Frontend"
url = "https://dev.trade-tariff.service.gov.uk/commodities/0101210000"
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 10.0
p90MediumWatermarkSeconds = 6.0
p90LowWatermarkSeconds = 1.0
concurrency = 2

[[application]]
name = "Trade Tariff Backend"
url = "https://dev.trade-tariff.service.gov.uk/api/v2/commodities/0101210000"
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 5.0
p90MediumWatermarkSeconds = 2.0
p90LowWatermarkSeconds = 1.0
concurrency = 2

[[application]]
name = "Trade Tariff FPO Search"
url = "https://search.dev.trade-tariff.service.gov.uk/fpo-code-search"
authHeader = "X-Api-Key"
authHeaderValue = "env:API_KEY"
verb = "POST"
data = '{"description":"cheesecake"}'
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 10.0
p90MediumWatermarkSeconds = 3.0
p90LowWatermarkSeconds = 1.0
concurrency = 2

[[application]]
name = "Trade Tariff Duty Calculator"
url = "https://dev.trade-tariff.service.gov.uk/duty-calculator/uk/0101210000/import-date"
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 10.0
p90MediumWatermarkSeconds = 3.0
p90LowWatermarkSeconds = 1.0
concurrency = 2

[[application]]
name = "Trade Tariff Admin"
url = "https://admin.dev.trade-tariff.service.gov.uk/healthcheck"
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 10.0
p90MediumWatermarkSeconds = 3.0
p90LowWatermarkSeconds = 1.0
concurrency = 2

[[application]]
name = "Trade Tariff Developer Hub Frontend"
url = "https://hub.dev.trade-tariff.service.gov.uk/healthcheck"
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 10.0
p90MediumWatermarkSeconds = 3.0
p90LowWatermarkSeconds = 1.0
concurrency = 2

[[application]]
name = "Trade Tariff Developer Hub Backend"
url = "https://hub.dev.trade-tariff.service.gov.uk/api/healthcheck"
errorHighWatermarkPercentage = 50.0
errorMediumWatermarkPercentage = 20.0
errorLowWatermarkPercentage = 1.0
p90HighWatermarkSeconds = 10.0
p90MediumWatermarkSeconds = 3.0
p90LowWatermarkSeconds = 1.0
concurrency = 2
